language: csharp
solution: ./SPLConqueror/SPLConqueror.sln
mono:
  - latest
install:
  - nuget restore ./SPLConqueror/SPLConqueror.sln
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner
script:
  - msbuild ./SPLConqueror/SPLConqueror.sln /t:Build
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe ./SPLConqueror/SamplingUnitTest/bin/Debug/SamplingUnitTest.dll