language: csharp
solution: ./SPLConqueror/SPLConqueror.sln
mono:
  - latest
install:
  - nuget restore ./SPLConqueror/SPLConqueror.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./SPLConqueror/SPLConqueror.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./SPLConqueror/SamplingUnitTest/bin/Release/SamplingUnitTest.dll