language: csharp
solution: ./SPLConqueror/SPLConqueror.sln
mono:
  - latest
install:
  - nuget restore ./SPLConqueror/SPLConqueror.sln #Download all packaged
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner #Additional to the Nunit test framework download the runner to execue the test.
before_script:
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.6.0/z3-4.6.0-x64-ubuntu-16.04.zip
  - 7z -e z3-4.6.0-x64-ubuntu-16.04.zip
  - mkdir -p TRAVIS_BUILD_DIR/SPLConqueror/packages/z3x64win.4.5.0.1/lib/
  - mv Microsoft.Z3.dll TRAVIS_BUILD_DIR/SPLConqueror/packages/z3x64win.4.5.0.1/lib/Microsoft.Z3.dll
script:
  - xbuild /p:Configuration=Debug ./SPLConqueror/SPLConqueror.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe ./SPLConqueror/SamplingUnitTest/bin/Debug/SamplingUnitTest.dll #Test sampling.
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe ./SPLConqueror/MachineLearningTest/bin/Debug/MachineLearningTest.dll #Test machine learning and a few command line commands.
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe ./SPLConqueror/SPLConquerorCoreTest/bin/Debug/SPLConquerorCoreTest.dll #Test core